### ISSUE TITLE
Consult the questions related to the model

### ISSUE THREAD

**Issue by xieshenru** [jdlamstein/happybot#1]
I did not find the tensorflow model for lower and upper face when I reproduced your code,andI did not find anything relevant online.Can you provide me with relevant models and information links?Thank you very much!

**Comment by iCiccio** [comment]
Hi, i didn't find too. Could you help me ? Thank you very much!

**Comment by jdlamstein** [comment]
Sorry for the delay, just added the files.

**Comment by iCiccio** [comment]
Thank you 😃
